version: "3.9"
services:
  rails:
    build: 
      context: .
      target: deploy
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - rails