version: "3.9"
services:
  rails:
    image: 208883155032.dkr.ecr.ap-northeast-1.amazonaws.com/gpc-lesson-rails:latest
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - rails
    restart: always