name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # - name: Docker Build
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
    #   run: |
    #     docker build --target deploy -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
    #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Image Deploy
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        HOST: ${{ secrets.DEPLOY_HOST }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        echo "$SSH_KEY" >> ssh_key && chmod 600 ssh_key
        ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@$HOST 'cd gpc-lesson-rails \
        && echo "$ECR_REGISTRY" >> hoge.txt \
        && aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${ECR_REGISTRY} \
        && docker-compose up -d'

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3